merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: default
    queue_conditions:
      - base~=(^main|^master|^stable/)
      - label=push
    merge_method: rebase
    update_bot_account: tianocore-issues
pull_request_rules:
  - name: Automatically merge a PR when all required checks pass and 'push' label is
      present
    conditions:
      - base~=(^main|^master|^stable/)
      - label=push
    actions:
      queue:
        name: default
  - name: Post a comment on a PR that can not be merged due to a merge conflict
    conditions:
      - base~=(^main|^master|^stable/)
      - conflict
    actions:
      comment:
        message: PR can not be merged due to conflict.  Please rebase and resubmit
priority_rules:
  - name: label automated or base is main
    priority: high
    conditions:
      - or:
          - label = automated
          - base = main
    allow_checks_interruption: true
